services:
  gzctf:
    image: gztime/gzctf:latest
    restart: always
    environment:
      - "GZCTF_ADMIN_PASSWORD=!Admin123"
      - "LC_ALL=en_US.UTF-8"
    ports:
      - "8080:8080"
    volumes:
      - "./data/files:/app/files"
      - "./appsettings.json:/app/appsettings.json:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - db
      - cache

  db:
    image: postgres:alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=db123"
    volumes:
      - "./data/db:/var/lib/postgresql/data"

  cache:
    image: ghcr.io/microsoft/garnet-alpine:latest
    command: ["--bind", "0.0.0.0"]
    restart: always

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data/minio:/data
