services:
  nginx:
    image: macbre/nginx-http3:latest
    user: root
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/log:/var/log/nginx
      - ./fullchain.pem:/cert/fullchain.pem:ro
      - ./privkey.pem:/cert/privkey.pem:ro
    network_mode: host

  registry:
    image: registry:latest
    restart: always
    ports:
      - "127.0.0.1:5000:5000/tcp"
    volumes:
      - ./data/registry:/var/lib/registry
    networks:
      - internal

  gzctf:
    image: gztime/gzctf:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080/tcp"
    environment:
      - "GZCTF_ADMIN_PASSWORD=!0CUWgMpTMUnm8QrmSvAFtlfc18Brv9F4"
      - "LC_ALL=en_US.UTF-8"
    volumes:
      - ./data/gzctf:/app/files
      - ./appsettings.json:/app/appsettings.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - cache
    networks:
      - internal

  db:
    image: postgres:latest
    restart: always
    environment:
      - "POSTGRES_PASSWORD=D1R7aUEhQqgNvMjqDpJiLMsrc9Nc08oI"
    volumes:
      - ./data/db:/var/lib/postgresql
    networks:
      - internal

  cache:
    image: ghcr.io/microsoft/garnet-alpine:latest
    command: ["--bind", "0.0.0.0"]
    restart: always
    networks:
      - internal

  minio:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "127.0.0.1:9000:9000/tcp"
      - "127.0.0.1:9001:9001/tcp"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: PBRFvS5K6ppDttNlvC2H5v4Qy2683Lf4
      MINIO_BROWSER_REDIRECT_URL: https://post-contest-cs-ubru-cyber-x-challenge-2025-ctf.noonomyen.com/bucket/console/
    volumes:
      - ./data/minio:/data
    networks:
      - internal

networks:
  internal:
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
